-- Create event_categories junction table
CREATE TABLE IF NOT EXISTS "public"."event_categories" (
    "event_id" BIGINT NOT NULL REFERENCES "public"."events"("id") ON DELETE CASCADE,
    "category_id" BIGINT NOT NULL REFERENCES "public"."categories"("id") ON DELETE CASCADE,
    "created_at" TIMESTAMP WITH TIME ZONE DEFAULT NOW() NOT NULL,
    PRIMARY KEY ("event_id", "category_id")
);

-- Create event_organizers junction table
CREATE TABLE IF NOT EXISTS "public"."event_organizers" (
    "event_id" BIGINT NOT NULL REFERENCES "public"."events"("id") ON DELETE CASCADE,
    "organizer_id" BIGINT NOT NULL REFERENCES "public"."organizers"("id") ON DELETE CASCADE,
    "created_at" TIMESTAMP WITH TIME ZONE DEFAULT NOW() NOT NULL,
    PRIMARY KEY ("event_id", "organizer_id")
);

-- Create event_sources table for tracking different event sources
CREATE TABLE IF NOT EXISTS "public"."event_sources" (
    "event_id" BIGINT NOT NULL REFERENCES "public"."events"("id") ON DELETE CASCADE,
    "source_type" TEXT NOT NULL CHECK (source_type IN ('facebook_source', 'meetup_source', 'custom_source')),
    "source_field" TEXT NOT NULL DEFAULT 'source_id',
    "source_id" TEXT NOT NULL,
    "created_at" TIMESTAMP WITH TIME ZONE DEFAULT NOW() NOT NULL,
    PRIMARY KEY ("event_id", "source_type")
);

-- Create facebook_source table
CREATE TABLE IF NOT EXISTS "public"."facebook_source" (
    "source_id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "source_type" TEXT NOT NULL DEFAULT 'page' CHECK (source_type IN ('page', 'account')),
    "event_link" TEXT,
    "event_detail" JSONB,
    "created_at" TIMESTAMP WITH TIME ZONE DEFAULT NOW() NOT NULL,
    "updated_at" TIMESTAMP WITH TIME ZONE DEFAULT NOW() NOT NULL
);

-- Create meetup_source table
CREATE TABLE IF NOT EXISTS "public"."meetup_source" (
    "source_id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "event_link" TEXT,
    "event_detail" JSONB,
    "created_at" TIMESTAMP WITH TIME ZONE DEFAULT NOW() NOT NULL,
    "updated_at" TIMESTAMP WITH TIME ZONE DEFAULT NOW() NOT NULL
);

-- Create eventbrite_source table
CREATE TABLE IF NOT EXISTS "public"."eventbrite_source" (
    "source_id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "event_link" TEXT,
    "event_detail" JSONB,
    "created_at" TIMESTAMP WITH TIME ZONE DEFAULT NOW() NOT NULL,
    "updated_at" TIMESTAMP WITH TIME ZONE DEFAULT NOW() NOT NULL
);

-- Create custom_source table
CREATE TABLE IF NOT EXISTS "public"."custom_source" (
    "source_id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "website_url" TEXT,
    "created_at" TIMESTAMP WITH TIME ZONE DEFAULT NOW() NOT NULL,
    "updated_at" TIMESTAMP WITH TIME ZONE DEFAULT NOW() NOT NULL
);

-- Add indexes for performance
CREATE INDEX IF NOT EXISTS "idx_event_categories_event" ON "public"."event_categories" USING btree ("event_id");
CREATE INDEX IF NOT EXISTS "idx_event_categories_category" ON "public"."event_categories" USING btree ("category_id");
CREATE INDEX IF NOT EXISTS "idx_event_organizers_event" ON "public"."event_organizers" USING btree ("event_id");
CREATE INDEX IF NOT EXISTS "idx_event_organizers_organizer" ON "public"."event_organizers" USING btree ("organizer_id");
CREATE INDEX IF NOT EXISTS "idx_event_sources_event" ON "public"."event_sources" USING btree ("event_id");
CREATE INDEX IF NOT EXISTS "idx_event_sources_type" ON "public"."event_sources" USING btree ("source_type");

-- Enable RLS
ALTER TABLE "public"."event_categories" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "public"."event_organizers" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "public"."event_sources" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "public"."facebook_source" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "public"."meetup_source" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "public"."custom_source" ENABLE ROW LEVEL SECURITY;

-- Create RLS policies for read access
CREATE POLICY "Enable read access for all users" ON "public"."event_categories"
    AS PERMISSIVE FOR SELECT TO public USING (true);

CREATE POLICY "Enable read access for all users" ON "public"."event_organizers"
    AS PERMISSIVE FOR SELECT TO public USING (true);

CREATE POLICY "Enable read access for all users" ON "public"."event_sources"
    AS PERMISSIVE FOR SELECT TO public USING (true);

CREATE POLICY "Enable read access for all users" ON "public"."facebook_source"
    AS PERMISSIVE FOR SELECT TO public USING (true);

CREATE POLICY "Enable read access for all users" ON "public"."meetup_source"
    AS PERMISSIVE FOR SELECT TO public USING (true);

CREATE POLICY "Enable read access for all users" ON "public"."custom_source"
    AS PERMISSIVE FOR SELECT TO public USING (true);

-- Grant permissions
GRANT ALL ON TABLE "public"."event_categories" TO "anon";
GRANT ALL ON TABLE "public"."event_categories" TO "authenticated";
GRANT ALL ON TABLE "public"."event_categories" TO "service_role";

GRANT ALL ON TABLE "public"."event_organizers" TO "anon";
GRANT ALL ON TABLE "public"."event_organizers" TO "authenticated";
GRANT ALL ON TABLE "public"."event_organizers" TO "service_role";

GRANT ALL ON TABLE "public"."event_sources" TO "anon";
GRANT ALL ON TABLE "public"."event_sources" TO "authenticated";
GRANT ALL ON TABLE "public"."event_sources" TO "service_role";

GRANT ALL ON TABLE "public"."facebook_source" TO "anon";
GRANT ALL ON TABLE "public"."facebook_source" TO "authenticated";
GRANT ALL ON TABLE "public"."facebook_source" TO "service_role";

GRANT ALL ON TABLE "public"."meetup_source" TO "anon";
GRANT ALL ON TABLE "public"."meetup_source" TO "authenticated";
GRANT ALL ON TABLE "public"."meetup_source" TO "service_role";

GRANT ALL ON TABLE "public"."custom_source" TO "anon";
GRANT ALL ON TABLE "public"."custom_source" TO "authenticated";
GRANT ALL ON TABLE "public"."custom_source" TO "service_role";

GRANT ALL ON SEQUENCE "public"."facebook_source_source_id_seq" TO "anon";
GRANT ALL ON SEQUENCE "public"."facebook_source_source_id_seq" TO "authenticated";
GRANT ALL ON SEQUENCE "public"."facebook_source_source_id_seq" TO "service_role";

GRANT ALL ON SEQUENCE "public"."meetup_source_source_id_seq" TO "anon";
GRANT ALL ON SEQUENCE "public"."meetup_source_source_id_seq" TO "authenticated";
GRANT ALL ON SEQUENCE "public"."meetup_source_source_id_seq" TO "service_role";

GRANT ALL ON SEQUENCE "public"."custom_source_source_id_seq" TO "anon";
GRANT ALL ON SEQUENCE "public"."custom_source_source_id_seq" TO "authenticated";
GRANT ALL ON SEQUENCE "public"."custom_source_source_id_seq" TO "service_role";