-- Multi-source attribution + multi-organizer schema.
--
-- Replaces the implicit "one event = one source_id, one account_id" model with
-- three relationships:
--   1. events ↔ source platforms (many)   via event_source_links
--   2. events ↔ co-organizing accounts (many) via event_organizers
--   3. accounts ↔ organizations (many-to-one) for editorial grouping
--
-- The legacy events.account_id / events.source / events.source_id columns are
-- kept for one release cycle as a safety net during the rollout. They can be
-- dropped once all readers have been migrated to the new tables.
--
-- Depends on 20260428120000_change_account_and_source_id_to_text.sql — assumes
-- accounts.account_id is already TEXT.

-- 1. pg_trgm enables trigram-based similarity matching for the deduplication
--    matcher. Cheap (single GIN index per column), in-database (no app-side
--    cost), and the operator (%) plays well with our nightly cron volume.
CREATE EXTENSION IF NOT EXISTS "pg_trgm" WITH SCHEMA "extensions";


-- 2. organizations — the editorial unit. JSCebu, PizzaPy, GOAB, etc. One row
--    per real-world community or solo host, regardless of how many platforms
--    they post on. The accounts table links many platform-presences to one row.
CREATE TABLE IF NOT EXISTS "public"."organizations" (
    "id" bigint NOT NULL,
    "name" text NOT NULL,
    "slug" text,
    "source_priority" text[],
    "primary_photo" text,
    "website" text,
    "is_individual" boolean NOT NULL DEFAULT false,
    "is_active" boolean NOT NULL DEFAULT true,
    "created_at" timestamp with time zone NOT NULL DEFAULT now(),
    "updated_at" timestamp with time zone NOT NULL DEFAULT now()
);
ALTER TABLE "public"."organizations" OWNER TO "postgres";
ALTER TABLE "public"."organizations"
    ALTER COLUMN "id" ADD GENERATED BY DEFAULT AS IDENTITY (
        SEQUENCE NAME "public"."organizations_id_seq"
        START WITH 1
        INCREMENT BY 1
        NO MINVALUE
        NO MAXVALUE
        CACHE 1
    );
ALTER TABLE ONLY "public"."organizations"
    ADD CONSTRAINT "organizations_pkey" PRIMARY KEY ("id");
ALTER TABLE ONLY "public"."organizations"
    ADD CONSTRAINT "organizations_slug_key" UNIQUE ("slug");

COMMENT ON TABLE "public"."organizations" IS 'Editorial grouping above accounts. PizzaPy / JSCebu / GOAB etc. — one row per community or solo host.';
COMMENT ON COLUMN "public"."organizations"."source_priority" IS 'Ordered preference, e.g. {luma,facebook,meetup}. NULL means use the global default. The matcher uses this to decide which scrape becomes the canonical content for events linked to this org.';
COMMENT ON COLUMN "public"."organizations"."is_individual" IS 'true for solo hosts (e.g., a Luma user with no associated calendar/community).';


-- 3. accounts gains:
--      organization_id — nullable; populated by admin grouping
--      kind            — platform-presence type (fb_page, luma_calendar, ...)
--    Existing rows are FB pages, so we backfill kind accordingly.
ALTER TABLE "public"."accounts"
    ADD COLUMN IF NOT EXISTS "organization_id" bigint
        REFERENCES "public"."organizations"("id") ON UPDATE CASCADE ON DELETE SET NULL;

ALTER TABLE "public"."accounts"
    ADD COLUMN IF NOT EXISTS "kind" text;

COMMENT ON COLUMN "public"."accounts"."organization_id" IS 'Optional grouping of multiple accounts under one editorial organization. NULL until an admin assigns it.';
COMMENT ON COLUMN "public"."accounts"."kind" IS 'Platform-presence kind: fb_page | luma_calendar | luma_user | meetup_group | eventbrite_organizer | unknown';

UPDATE "public"."accounts"
   SET "kind" = 'fb_page'
 WHERE "kind" IS NULL AND "type" = 'facebook';


-- 4. event_source_links — every place we found this event. UNIQUE(source,
--    source_id) preserves the de-dup constraint that previously lived on
--    events.source_id, but now at the link level so one event can have many.
CREATE TABLE IF NOT EXISTS "public"."event_source_links" (
    "id" bigint NOT NULL,
    "event_id" bigint NOT NULL,
    "source" text NOT NULL,
    "source_id" text NOT NULL,
    "url" text,
    "scraped_at" timestamp with time zone NOT NULL DEFAULT now(),
    "raw" jsonb,
    "created_at" timestamp with time zone NOT NULL DEFAULT now()
);
ALTER TABLE "public"."event_source_links" OWNER TO "postgres";
ALTER TABLE "public"."event_source_links"
    ALTER COLUMN "id" ADD GENERATED BY DEFAULT AS IDENTITY (
        SEQUENCE NAME "public"."event_source_links_id_seq"
        START WITH 1
        INCREMENT BY 1
        NO MINVALUE
        NO MAXVALUE
        CACHE 1
    );
ALTER TABLE ONLY "public"."event_source_links"
    ADD CONSTRAINT "event_source_links_pkey" PRIMARY KEY ("id");
ALTER TABLE ONLY "public"."event_source_links"
    ADD CONSTRAINT "event_source_links_event_id_fkey"
    FOREIGN KEY ("event_id") REFERENCES "public"."events"("id") ON DELETE CASCADE;
ALTER TABLE ONLY "public"."event_source_links"
    ADD CONSTRAINT "event_source_links_source_uniq" UNIQUE ("source", "source_id");
CREATE INDEX IF NOT EXISTS "event_source_links_event_id_idx"
    ON "public"."event_source_links" USING btree ("event_id");

COMMENT ON TABLE "public"."event_source_links" IS 'Many-to-one to events. One row per platform-presence (FB event, Luma event, Meetup event). The UNIQUE(source, source_id) constraint replaces the legacy events.source_id UNIQUE — same dedup guarantee, now at the link level.';
COMMENT ON COLUMN "public"."event_source_links"."raw" IS 'Full scraped payload, kept for diff/audit and for re-materializing canonical content if the org switches its source_priority.';


-- 5. event_organizers — many-to-many between events and accounts.
--    Replaces the events.account_id single-FK so co-organized events can
--    correctly attribute to all hosting accounts (PizzaPy + JSCebu + AWSUG).
CREATE TABLE IF NOT EXISTS "public"."event_organizers" (
    "event_id" bigint NOT NULL,
    "account_id" text NOT NULL,
    "role" text NOT NULL DEFAULT 'host',
    "position" integer NOT NULL DEFAULT 0,
    "created_at" timestamp with time zone NOT NULL DEFAULT now()
);
ALTER TABLE "public"."event_organizers" OWNER TO "postgres";
ALTER TABLE ONLY "public"."event_organizers"
    ADD CONSTRAINT "event_organizers_pkey" PRIMARY KEY ("event_id", "account_id");
ALTER TABLE ONLY "public"."event_organizers"
    ADD CONSTRAINT "event_organizers_event_id_fkey"
    FOREIGN KEY ("event_id") REFERENCES "public"."events"("id") ON DELETE CASCADE;
ALTER TABLE ONLY "public"."event_organizers"
    ADD CONSTRAINT "event_organizers_account_id_fkey"
    FOREIGN KEY ("account_id") REFERENCES "public"."accounts"("account_id")
    ON UPDATE CASCADE ON DELETE CASCADE;
CREATE INDEX IF NOT EXISTS "event_organizers_account_id_idx"
    ON "public"."event_organizers" USING btree ("account_id");

COMMENT ON TABLE "public"."event_organizers" IS 'Many-to-many: events ↔ accounts. position=0 is the primary host (kept in scrape order).';
COMMENT ON COLUMN "public"."event_organizers"."role" IS 'Reserved for future roles like co-host, sponsor, speaker. Defaults to host.';


-- 6. events.primary_source_link_id — which source_link''s content is the
--    currently-canonical version. Nullable during transition; the matcher
--    sets/updates it according to the org''s source_priority.
ALTER TABLE "public"."events"
    ADD COLUMN IF NOT EXISTS "primary_source_link_id" bigint
        REFERENCES "public"."event_source_links"("id") ON DELETE SET NULL;

COMMENT ON COLUMN "public"."events"."primary_source_link_id" IS 'Which event_source_links row is the source-of-truth for this event''s canonical content. Updated by the matcher per the owning organization''s source_priority.';


-- 7. Trigram index on event names. Enables similarity()-based matching to
--    return in milliseconds even on tens of thousands of rows.
CREATE INDEX IF NOT EXISTS "events_name_trgm_idx"
    ON "public"."events" USING gin ("name" extensions.gin_trgm_ops);


-- 8. find_event_matches — convenience RPC the ingest pipeline calls to look
--    up candidate matches. Returns at most 5 events scoring above threshold,
--    ordered by score desc. Window is a date range to keep the index walk
--    cheap; matches must be within ±N days (default 1, accommodates timezone
--    bugs and events that span midnight).
CREATE OR REPLACE FUNCTION public.find_event_matches(
    p_name text,
    p_start_time timestamptz,
    p_threshold real DEFAULT 0.7,
    p_window_days int DEFAULT 1
)
RETURNS TABLE(id bigint, name text, score real)
LANGUAGE sql
STABLE
AS $$
    SELECT
        e.id,
        e.name,
        extensions.similarity(e.name, p_name) AS score
    FROM public.events e
    WHERE e.start_time BETWEEN p_start_time - (p_window_days || ' days')::interval
                           AND p_start_time + (p_window_days || ' days')::interval
      AND e.name IS NOT NULL
      AND extensions.similarity(e.name, p_name) >= p_threshold
    ORDER BY score DESC
    LIMIT 5;
$$;

GRANT EXECUTE ON FUNCTION public.find_event_matches(text, timestamptz, real, int) TO anon, authenticated, service_role;


-- 9. Backfill — every existing event becomes its own one-link, one-organizer
--    cluster. Idempotent via NOT EXISTS guards so re-running the migration
--    after a partial run is safe.
INSERT INTO "public"."event_source_links" ("event_id", "source", "source_id", "url", "scraped_at")
SELECT
    e.id,
    COALESCE(e.source, 'unknown'),
    -- The few historical rows with NULL source_id get a synthetic placeholder
    -- so we don''t violate NOT NULL on the link. They''ll never collide with
    -- real source IDs (which never start with "legacy-").
    COALESCE(e.source_id, 'legacy-' || e.id::text),
    e.ticket_url,
    e.created_at
FROM "public"."events" e
WHERE NOT EXISTS (
    SELECT 1 FROM "public"."event_source_links" esl WHERE esl.event_id = e.id
);

UPDATE "public"."events" e
   SET "primary_source_link_id" = esl.id
  FROM "public"."event_source_links" esl
 WHERE esl.event_id = e.id
   AND e."primary_source_link_id" IS NULL;

INSERT INTO "public"."event_organizers" ("event_id", "account_id", "role", "position")
SELECT e.id, e.account_id, 'host', 0
FROM "public"."events" e
WHERE e.account_id IS NOT NULL
  AND NOT EXISTS (
      SELECT 1 FROM "public"."event_organizers" eo
      WHERE eo.event_id = e.id AND eo.account_id = e.account_id
  );


-- 10. Permissions — mirror the existing tables (anon/authenticated/service_role)
GRANT ALL ON TABLE "public"."organizations" TO "anon";
GRANT ALL ON TABLE "public"."organizations" TO "authenticated";
GRANT ALL ON TABLE "public"."organizations" TO "service_role";
GRANT ALL ON SEQUENCE "public"."organizations_id_seq" TO "anon";
GRANT ALL ON SEQUENCE "public"."organizations_id_seq" TO "authenticated";
GRANT ALL ON SEQUENCE "public"."organizations_id_seq" TO "service_role";

GRANT ALL ON TABLE "public"."event_source_links" TO "anon";
GRANT ALL ON TABLE "public"."event_source_links" TO "authenticated";
GRANT ALL ON TABLE "public"."event_source_links" TO "service_role";
GRANT ALL ON SEQUENCE "public"."event_source_links_id_seq" TO "anon";
GRANT ALL ON SEQUENCE "public"."event_source_links_id_seq" TO "authenticated";
GRANT ALL ON SEQUENCE "public"."event_source_links_id_seq" TO "service_role";

GRANT ALL ON TABLE "public"."event_organizers" TO "anon";
GRANT ALL ON TABLE "public"."event_organizers" TO "authenticated";
GRANT ALL ON TABLE "public"."event_organizers" TO "service_role";
