-- ============================================================================
-- Cebby v2 — initial schema
-- ============================================================================
--
-- Single coherent migration for a fresh Supabase project. Replaces the
-- accreted v1 schema (services/core/supabase/migrations/) with a clean
-- design grounded in:
--
--   • .impeccable.md  — Cebby is a calm, public-utility directory. Not an
--                       organizer toolkit, not RSVP, not a community network.
--                       The whitelist is the moat.
--   • ARCHITECTURE.md — multi-source attribution model.
--
-- Conventions used throughout:
--   • bigint IDs with GENERATED BY DEFAULT AS IDENTITY (lets the migration
--     script preserve v1 numeric ids during cutover).
--   • Every user-content table has created_at + updated_at maintained via
--     trigger. updated_at powers HTTP cache validation at the edge.
--   • Foreign keys are explicit about ON DELETE behavior — CASCADE only for
--     genuinely owned children, SET NULL for soft links.
--   • Status as an enum type, not a boolean. is_hidden conflates several
--     real states (draft, hidden, cancelled).
--
-- Dormant tables (profiles, event_registrations) are preserved verbatim from
-- v1 so the PWA's Wrapped feature keeps working. They are NOT to be developed
-- further per impeccable.md.
-- ============================================================================


-- ----------------------------------------------------------------------------
-- 1. Extensions
-- ----------------------------------------------------------------------------

-- pg_trgm: trigram similarity for the event-deduplication matcher.
CREATE EXTENSION IF NOT EXISTS "pg_trgm" WITH SCHEMA "extensions";

-- pgcrypto: gen_random_uuid() for the dormant profiles table.
CREATE EXTENSION IF NOT EXISTS "pgcrypto" WITH SCHEMA "extensions";


-- ----------------------------------------------------------------------------
-- 2. Enum types
-- ----------------------------------------------------------------------------

-- Event lifecycle. Replaces v1.events.is_hidden boolean which conflated
-- "hidden by admin" with "cancelled by organizer" — distinct states that
-- need distinct UI treatment ("Event has been cancelled" vs invisible).
CREATE TYPE "public"."event_status" AS ENUM (
    'draft',      -- internal, not yet published
    'published',  -- live in the directory (default)
    'hidden',     -- admin-suppressed (spam, duplicate, low quality)
    'cancelled'   -- organizer cancelled — keep visible with strikethrough
);

-- Whether an event happens in person, online, or both. Derived at ingest
-- from location_type / virtual_info; stored explicitly so filter chips
-- don't have to text-match "Online" prefixes.
CREATE TYPE "public"."event_format" AS ENUM (
    'in_person',
    'online',
    'hybrid'
);

-- How a row entered our system. Drives source_priority defaults: a
-- partnership-tokenized FB scrape outranks an HTML-scraped Luma page for
-- the same event. Manual takes precedence over everything for hand-edits.
CREATE TYPE "public"."ingest_kind" AS ENUM (
    'manual',         -- admin-entered or admin-edited
    'partnership',    -- tokenized API access via formal partnership (FB pages)
    'public_api',     -- documented public API (none today; reserved)
    'public_scrape'   -- HTML / __NEXT_DATA__ extraction (default)
);


-- ----------------------------------------------------------------------------
-- 3. Trigger function — set_updated_at
-- ----------------------------------------------------------------------------

CREATE OR REPLACE FUNCTION "public"."set_updated_at"()
RETURNS trigger
LANGUAGE plpgsql
AS $$
BEGIN
    NEW.updated_at = now();
    RETURN NEW;
END;
$$;


-- ============================================================================
-- 4. ACTIVE TABLES (designed v2)
-- ============================================================================


-- ----------------------------------------------------------------------------
-- organizations — the editorial unit. JSCebu / GOAB / PizzaPy etc.
-- One row per real-world community or solo host, regardless of platforms.
-- This table IS the whitelist (verified_at = trust signal).
-- ----------------------------------------------------------------------------

CREATE TABLE "public"."organizations" (
    "id"                  bigint        NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    "slug"                text          NOT NULL,
    "name"                text          NOT NULL,
    "tagline"             text,                       -- one-line description shown on cards
    "description"         text,                       -- markdown ok, longer-form
    "primary_photo"       text,                       -- logo / avatar URL (R2)
    "cover_photo"         text,                       -- banner image URL (R2)

    -- Geographic anchor (PH-wide flexibility per design discussion).
    "city"                text,
    "region"              text,
    "country"             text          DEFAULT 'PH',

    -- Lead-contact metadata. Free-text by design — we explicitly chose
    -- not to model "people" as relational entities (see design notes).
    -- If a partner has multiple leads, list them comma-separated in
    -- lead_contact_name. Upgrade path: split into a persons table later
    -- if/when speaker profiles get prioritized.
    "lead_contact_name"   text,
    "lead_contact_email"  text,
    "lead_contact_role"   text,         -- "Founder", "Lead Organizer"

    -- {twitter, instagram, linkedin, facebook, youtube, tiktok, website}.
    -- jsonb instead of separate columns because the set churns; admin UI
    -- can validate keys against a known list without a schema migration.
    "social_links"        jsonb,
    "founded_year"        int,

    -- Per-org override of the default source priority. NULL = use global
    -- default ['luma', 'facebook', 'meetup', 'eventbrite', 'website'].
    "source_priority"     text[],

    -- Whitelist marker. Set BY HAND when a partnership is established.
    -- The PWA shows a checkmark next to verified orgs. This field is the
    -- single most-load-bearing piece of editorial state in the DB.
    "verified_at"         timestamptz,

    "is_individual"       boolean       NOT NULL DEFAULT false,
    "is_active"           boolean       NOT NULL DEFAULT true,

    "created_at"          timestamptz   NOT NULL DEFAULT now(),
    "updated_at"          timestamptz   NOT NULL DEFAULT now(),

    PRIMARY KEY ("id"),
    UNIQUE ("slug")
);

COMMENT ON TABLE  "public"."organizations" IS 'Editorial whitelist. One row per real-world community / solo host. verified_at = the partnership stamp shown as a checkmark in the PWA.';
COMMENT ON COLUMN "public"."organizations"."verified_at" IS 'Set by hand when a partnership is established. Drives the verified-organizer badge. The PWA aggregates non-verified orgs too, but only verified ones get the trust signal.';
COMMENT ON COLUMN "public"."organizations"."source_priority" IS 'Per-org override of canonical-content priority. NULL = use global default.';
COMMENT ON COLUMN "public"."organizations"."social_links" IS 'jsonb keyed by platform: {twitter, instagram, linkedin, facebook, youtube, tiktok, website}. Admin UI validates keys.';

CREATE TRIGGER "set_organizations_updated_at"
    BEFORE UPDATE ON "public"."organizations"
    FOR EACH ROW EXECUTE FUNCTION "public"."set_updated_at"();


-- ----------------------------------------------------------------------------
-- accounts — per-platform identity. One row per FB page, Luma calendar,
-- Luma user, Meetup group, etc. account_id is the platform's stable ID
-- (text — Luma's "cal-..." / "usr-..." don't fit bigint).
-- ----------------------------------------------------------------------------

CREATE TABLE "public"."accounts" (
    -- Platform-stable text id is the natural PK. v1 had a redundant bigint
    -- "id" that nothing pointed at — dropped here.
    "account_id"        text          NOT NULL,
    "name"              text          NOT NULL,

    -- Source platform: 'facebook' | 'luma' | 'meetup' | 'eventbrite'.
    "type"              text          NOT NULL,

    -- Platform-presence kind. Tells us which scraper code path applies
    -- and what shape account_details holds.
    --   fb_page | luma_calendar | luma_user | meetup_group | eventbrite_organizer
    "kind"              text          NOT NULL,

    "primary_photo"     text,

    -- Promoted from v1.account_details.path. The seed string the cron
    -- functions use to discover this account's events:
    --   'awsugcebu'      — Luma calendar slug
    --   'user/lisksea'   — Luma user handle path
    --   'pizzapy'        — FB page username
    "discovery_path"    text,

    -- Genuinely platform-specific blob — kept narrow.
    -- For FB: { internal_page_id?, locale? }
    -- For Luma: { user_api_id?, calendar_admin_user? }
    "account_details"   jsonb,

    -- How we obtain data from this account. Drives canonical-content
    -- priority — partnership beats public_scrape for the same event.
    "ingest_kind"       "public"."ingest_kind" NOT NULL DEFAULT 'public_scrape',

    -- Editorial grouping: many accounts can belong to one organization.
    -- (PizzaPy's FB page + Luma calendar both link to org "PizzaPy".)
    "organization_id"   bigint
        REFERENCES "public"."organizations"("id")
        ON UPDATE CASCADE ON DELETE SET NULL,

    "is_active"         boolean       NOT NULL DEFAULT true,

    "created_at"        timestamptz   NOT NULL DEFAULT now(),
    "updated_at"        timestamptz   NOT NULL DEFAULT now(),

    PRIMARY KEY ("account_id")
);

COMMENT ON TABLE  "public"."accounts" IS 'Per-platform identity. One row per FB page / Luma calendar / Luma user / Meetup group / etc. account_id is the platform-stable text id.';
COMMENT ON COLUMN "public"."accounts"."discovery_path" IS 'Seed string the cron jobs use to discover events. Promoted from v1 account_details.path for type-safety.';
COMMENT ON COLUMN "public"."accounts"."ingest_kind" IS 'Reliability tier of how we obtain data from this account. Partnership > public_api > public_scrape > manual (where manual takes precedence for hand-edits).';


-- ----------------------------------------------------------------------------
-- account_secrets — sensitive auth material kept apart from the public-
-- readable accounts row. Service-role-only access. (FB page tokens etc.)
-- ----------------------------------------------------------------------------

CREATE TABLE "public"."account_secrets" (
    "account_id"        text          NOT NULL,

    "access_token"        text,
    "page_access_token"   text,
    "refresh_token"       text,
    "expires_at"          timestamptz,
    "rotated_at"          timestamptz,

    "created_at"          timestamptz   NOT NULL DEFAULT now(),
    "updated_at"          timestamptz   NOT NULL DEFAULT now(),

    PRIMARY KEY ("account_id"),
    FOREIGN KEY ("account_id") REFERENCES "public"."accounts"("account_id")
        ON UPDATE CASCADE ON DELETE CASCADE
);

COMMENT ON TABLE "public"."account_secrets" IS 'Sensitive auth material split from accounts. RLS restricts to service_role. Never expose via PostgREST.';

CREATE TRIGGER "set_accounts_updated_at"
    BEFORE UPDATE ON "public"."accounts"
    FOR EACH ROW EXECUTE FUNCTION "public"."set_updated_at"();

CREATE TRIGGER "set_account_secrets_updated_at"
    BEFORE UPDATE ON "public"."account_secrets"
    FOR EACH ROW EXECUTE FUNCTION "public"."set_updated_at"();


-- ----------------------------------------------------------------------------
-- venues — physical place reusable across events.
-- Optional: events without a venue keep a free-text events.location.
-- An organization can own a venue (enspace, Innovation Hub) so we can
-- show "events at enspace" pages.
-- ----------------------------------------------------------------------------

CREATE TABLE "public"."venues" (
    "id"             bigint        NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    "slug"           text          NOT NULL,
    "name"           text          NOT NULL,
    "address_line"   text,
    "city"           text,
    "region"         text,
    "country"        text          DEFAULT 'PH',

    -- jsonb { latitude, longitude } — same shape as v1 events.location_details.
    -- PostGIS would be nicer but adds an extension dependency for marginal
    -- gain at our scale. Upgradeable later.
    "coordinate"     jsonb,

    "capacity"       int,
    "primary_photo"  text,

    -- Org that owns/operates this venue (e.g. enspace owns its venue).
    -- NULL for community venues we don't attribute.
    "parent_org_id"  bigint
        REFERENCES "public"."organizations"("id")
        ON UPDATE CASCADE ON DELETE SET NULL,

    -- Verified venue = admin has confirmed this isn't a typo / merger
    -- candidate. Useful for /venues/[slug] page eligibility.
    "is_verified"    boolean       NOT NULL DEFAULT false,
    "is_active"      boolean       NOT NULL DEFAULT true,

    "created_at"     timestamptz   NOT NULL DEFAULT now(),
    "updated_at"     timestamptz   NOT NULL DEFAULT now(),

    PRIMARY KEY ("id"),
    UNIQUE ("slug")
);

COMMENT ON TABLE "public"."venues" IS 'Physical place reusable across events. NULL on online events. Slug-stable for /venues/[slug] pages.';

CREATE TRIGGER "set_venues_updated_at"
    BEFORE UPDATE ON "public"."venues"
    FOR EACH ROW EXECUTE FUNCTION "public"."set_updated_at"();


-- ----------------------------------------------------------------------------
-- events — canonical event row. Content here is overwritten by the
-- highest-priority source per source_priority rules. Original raw
-- payloads stay in event_source_links.raw.
-- ----------------------------------------------------------------------------

CREATE TABLE "public"."events" (
    "id"                       bigint                  NOT NULL GENERATED BY DEFAULT AS IDENTITY,

    "name"                     text                    NOT NULL,
    "description"              text,

    -- Time, with named timezone preserved separately. start_time stores
    -- the offset Luma/FB emit; timezone (e.g. 'Asia/Manila') is the named
    -- zone for display ("8 PM PHT") and DST-safe future calculations.
    "start_time"               timestamptz             NOT NULL,
    "end_time"                 timestamptz,
    "timezone"                 text,

    -- Free-text location string — fallback for events without a venue
    -- (online, "TBD", "somewhere downtown"). When venue_id is set, the
    -- venue's name/address is canonical.
    "location"                 text,

    -- Coordinates for unmapped venues (geocoded on ingest). Redundant
    -- with venues.coordinate when venue_id is set; keep both because not
    -- every event becomes a venue row.
    "location_details"         jsonb,

    "venue_id"                 bigint
        REFERENCES "public"."venues"("id")
        ON UPDATE CASCADE ON DELETE SET NULL,

    -- Denormalized geographic fields (work for online events too — an
    -- online event "from Cebu City" is a valid editorial classification).
    -- Trigger could sync from venue but easier to write at ingest time.
    "city"                     text,
    "region"                   text,
    "country"                  text                    DEFAULT 'PH',

    -- Image fields. cover_photo is the canonical R2 URL. cover_blurhash
    -- is the 30-char placeholder shown instantly during card render —
    -- improves LCP on card lists by ~300ms in our testing.
    "cover_photo"              text,
    "cover_blurhash"           text,

    "status"                   "public"."event_status" NOT NULL DEFAULT 'published',
    "format"                   "public"."event_format" NOT NULL DEFAULT 'in_person',

    -- Free/paid signal for the "Free" filter chip. NULL = unknown
    -- (don't claim an event is free when we don't know).
    "is_free"                  boolean,
    "price_min"                numeric,
    "price_max"                numeric,
    "currency"                 text                    DEFAULT 'PHP',

    -- Editorial features.
    "is_featured"              boolean                 NOT NULL DEFAULT false,

    -- Slug stays denormalized on events for fast single-row reads. The
    -- full slug history lives in event_slugs (so old URLs keep working
    -- after a rename). events.slug is always == the row in event_slugs
    -- where is_current=true.
    "slug"                     text,

    -- Which event_source_links row holds the source-of-truth content.
    -- Updated by the matcher per the owning org's source_priority.
    "primary_source_link_id"   bigint,

    "created_at"               timestamptz             NOT NULL DEFAULT now(),
    "updated_at"               timestamptz             NOT NULL DEFAULT now(),

    PRIMARY KEY ("id"),
    UNIQUE ("slug")
);

COMMENT ON TABLE  "public"."events" IS 'Canonical event row. Content here is the highest-priority source''s version per the owning org''s source_priority. All raw payloads live in event_source_links.raw.';
COMMENT ON COLUMN "public"."events"."status" IS 'Lifecycle: draft (internal), published (default, live), hidden (admin-suppressed), cancelled (organizer cancelled, keep visible).';
COMMENT ON COLUMN "public"."events"."cover_blurhash" IS '30-char placeholder for instant LCP. Computed at ingest from cover_photo.';
COMMENT ON COLUMN "public"."events"."primary_source_link_id" IS 'Which event_source_links row''s content is currently canonical. Updated by the ingest pipeline based on source_priority.';

CREATE TRIGGER "set_events_updated_at"
    BEFORE UPDATE ON "public"."events"
    FOR EACH ROW EXECUTE FUNCTION "public"."set_updated_at"();


-- ----------------------------------------------------------------------------
-- event_source_links — every place we found this event. Many-to-one to
-- events. Original raw payload preserved here for diff/audit and for
-- re-deriving canonical content if the org switches source priority.
-- ----------------------------------------------------------------------------

CREATE TABLE "public"."event_source_links" (
    "id"            bigint                   NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    "event_id"      bigint                   NOT NULL,

    -- Source platform: 'facebook' | 'luma' | 'meetup' | 'eventbrite' | 'website' | 'manual'
    "source"        text                     NOT NULL,
    -- Platform-specific event id (FB graph id, Luma 'evt-...', etc).
    "source_id"     text                     NOT NULL,
    "url"           text,

    -- Reliability tier of this specific scrape (may differ from the
    -- account's default — e.g. a manual override).
    "ingest_kind"   "public"."ingest_kind"   NOT NULL DEFAULT 'public_scrape',

    "scraped_at"    timestamptz              NOT NULL DEFAULT now(),

    -- Full raw payload from the source. Trim periodically (>12mo) to
    -- keep DB size bounded — see runbook.
    "raw"           jsonb,

    "created_at"    timestamptz              NOT NULL DEFAULT now(),
    "updated_at"    timestamptz              NOT NULL DEFAULT now(),

    PRIMARY KEY ("id"),
    UNIQUE ("source", "source_id"),
    FOREIGN KEY ("event_id") REFERENCES "public"."events"("id")
        ON DELETE CASCADE
);

COMMENT ON TABLE "public"."event_source_links" IS 'Many-to-one to events. One row per platform-presence. UNIQUE(source, source_id) ensures each external event becomes at most one link.';

CREATE TRIGGER "set_event_source_links_updated_at"
    BEFORE UPDATE ON "public"."event_source_links"
    FOR EACH ROW EXECUTE FUNCTION "public"."set_updated_at"();

-- Now that event_source_links exists, the FK from events back to it can be added.
ALTER TABLE "public"."events"
    ADD CONSTRAINT "events_primary_source_link_id_fkey"
    FOREIGN KEY ("primary_source_link_id")
    REFERENCES "public"."event_source_links"("id")
    ON DELETE SET NULL;


-- ----------------------------------------------------------------------------
-- event_organizers — many-to-many events ↔ accounts.
-- position=0 is the primary host (kept in scrape order).
-- ----------------------------------------------------------------------------

CREATE TABLE "public"."event_organizers" (
    "event_id"    bigint        NOT NULL,
    "account_id"  text          NOT NULL,
    "role"        text          NOT NULL DEFAULT 'host',
    "position"    int           NOT NULL DEFAULT 0,
    "created_at"  timestamptz   NOT NULL DEFAULT now(),

    PRIMARY KEY ("event_id", "account_id"),
    FOREIGN KEY ("event_id") REFERENCES "public"."events"("id") ON DELETE CASCADE,
    FOREIGN KEY ("account_id") REFERENCES "public"."accounts"("account_id")
        ON UPDATE CASCADE ON DELETE CASCADE
);

COMMENT ON TABLE  "public"."event_organizers" IS 'Many-to-many between events and accounts. position=0 = primary host (the "Presented by" entity).';
COMMENT ON COLUMN "public"."event_organizers"."role" IS 'presenter | cohost | host. Reserved for expansion (sponsor, partner) but speakers explicitly NOT modeled here per impeccable.md.';


-- ----------------------------------------------------------------------------
-- event_slugs — slug history for URL stability.
-- When an event is renamed, the old slug stays here forever pointing at
-- the same event_id. Old URLs always resolve.
-- ----------------------------------------------------------------------------

CREATE TABLE "public"."event_slugs" (
    "slug"         text          NOT NULL,
    "event_id"     bigint        NOT NULL,
    "is_current"   boolean       NOT NULL DEFAULT true,
    "created_at"   timestamptz   NOT NULL DEFAULT now(),

    PRIMARY KEY ("slug"),
    FOREIGN KEY ("event_id") REFERENCES "public"."events"("id")
        ON UPDATE CASCADE ON DELETE CASCADE
);

COMMENT ON TABLE "public"."event_slugs" IS 'Slug history. Old slugs keep pointing at the same event so URLs never 404 after a rename.';

-- A single event can only have one is_current=true slug.
CREATE UNIQUE INDEX "event_slugs_one_current_per_event"
    ON "public"."event_slugs" ("event_id")
    WHERE "is_current" = true;


-- ----------------------------------------------------------------------------
-- tags — editorial taxonomy. Filter chips on the PWA come from here
-- where is_canonical=true. Auto-detected tags (LLM/keyword) sit at
-- is_canonical=false until an admin promotes them.
-- ----------------------------------------------------------------------------

CREATE TABLE "public"."tags" (
    "id"             bigint        NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    "slug"           text          NOT NULL,
    "name"           text          NOT NULL,

    -- topic | format | level | language | other
    --   topic    — ai, blockchain, web3, design, devops, mobile, security, data
    --   format   — talk, workshop, hackathon, conference, meetup, social
    --   level    — beginner, intermediate, advanced, all_levels
    --   language — english, filipino, cebuano
    --   other    — free, hiring, networking
    "kind"           text          NOT NULL,

    -- true = appears as a filter chip / on org pages.
    -- false = scraper-suggested, awaiting admin review.
    "is_canonical"   boolean       NOT NULL DEFAULT false,

    "description"    text,         -- admin guidance: "Apply when ≥30% of talks are AI-focused"
    "color"          text,         -- optional hex for chip color override

    "created_at"     timestamptz   NOT NULL DEFAULT now(),
    "updated_at"     timestamptz   NOT NULL DEFAULT now(),

    PRIMARY KEY ("id"),
    UNIQUE ("slug")
);

COMMENT ON TABLE  "public"."tags" IS 'Editorial taxonomy. Filter chips come from is_canonical=true. Scraper-suggested tags wait at is_canonical=false until promoted.';
COMMENT ON COLUMN "public"."tags"."kind" IS 'topic | format | level | language | other. Drives chip groupings in the PWA filter UI.';

CREATE TRIGGER "set_tags_updated_at"
    BEFORE UPDATE ON "public"."tags"
    FOR EACH ROW EXECUTE FUNCTION "public"."set_updated_at"();


-- ----------------------------------------------------------------------------
-- event_tags — many-to-many between events and tags. source distinguishes
-- editorial decisions from auto-suggestions so we can re-run extraction
-- without losing curation.
-- ----------------------------------------------------------------------------

CREATE TABLE "public"."event_tags" (
    "event_id"    bigint        NOT NULL,
    "tag_id"      bigint        NOT NULL,

    -- 'manual'  — admin set this tag
    -- 'auto'    — keyword/LLM extraction (re-runnable)
    -- 'scraper' — copied from source platform's own tags (rare)
    "source"      text          NOT NULL DEFAULT 'manual',

    -- For auto-tags: 0..1 confidence. Lets the admin filter by quality.
    "confidence"  real,

    "created_at"  timestamptz   NOT NULL DEFAULT now(),

    PRIMARY KEY ("event_id", "tag_id"),
    FOREIGN KEY ("event_id") REFERENCES "public"."events"("id") ON DELETE CASCADE,
    FOREIGN KEY ("tag_id")   REFERENCES "public"."tags"("id")   ON DELETE CASCADE
);

COMMENT ON TABLE  "public"."event_tags" IS 'M:N between events and tags. source=manual is editorial; source=auto is re-derivable.';


-- ============================================================================
-- 5. DORMANT TABLES (preserved verbatim from v1 — not actively developed)
--
-- Per impeccable.md: RSVP-on-Cebby is killed, but profiles/event_registrations
-- still serve the Wrapped feature. They stay untouched here so the existing
-- API routes (apps/pwa/src/pages/api/wrapped-data.ts, my-events.ts, profile.ts,
-- rsvp-cancel.ts, walkin-registration.ts) keep compiling and running.
--
-- DO NOT add features against these. DO NOT remove them either.
-- ============================================================================

CREATE TABLE "public"."profiles" (
    "id"               uuid          PRIMARY KEY DEFAULT gen_random_uuid(),
    "logto_user_id"    varchar(255)  UNIQUE NOT NULL,
    "name"             varchar(255),
    "email"            varchar(255)  UNIQUE NOT NULL,
    "avatar_url"       text,
    "bio"              text,
    "contact_details"  jsonb         DEFAULT '{}'::jsonb,
    "social_links"     jsonb         DEFAULT '{}'::jsonb,
    "metadata"         jsonb         DEFAULT '{}'::jsonb,
    "created_at"       timestamptz   DEFAULT timezone('utc'::text, now()),
    "updated_at"       timestamptz   DEFAULT timezone('utc'::text, now()),
    "deleted_at"       timestamptz
);

CREATE INDEX "idx_profiles_logto_user_id" ON "public"."profiles" ("logto_user_id");
CREATE INDEX "idx_profiles_email"         ON "public"."profiles" ("email");

COMMENT ON TABLE "public"."profiles" IS 'DORMANT. Logto-backed user profiles. Used by Wrapped + dormant RSVP flows. Do not develop further (see .impeccable.md).';


CREATE TABLE "public"."event_registrations" (
    "id"                  uuid          DEFAULT gen_random_uuid() PRIMARY KEY,
    "event_id"            bigint        NOT NULL REFERENCES "public"."events"("id") ON DELETE CASCADE,
    "profile_id"          uuid          REFERENCES "public"."profiles"("id"),

    "name"                text          NOT NULL,
    "email"               text          NOT NULL,
    "phone"               varchar(50),

    "registered_at"       timestamptz   NOT NULL DEFAULT now(),
    "confirmed_at"        timestamptz,
    "cancelled_at"        timestamptz,
    "verification_token"  uuid,

    "checked_in_at"       timestamptz,
    "check_in_method"     varchar(50),
    "qr_code_id"          varchar(255)  UNIQUE,

    "status"              text          NOT NULL CHECK (status IN ('pending', 'confirmed', 'cancelled', 'declined', 'waitlisted', 'walkin')),
    "type"                varchar(50)   DEFAULT 'online',

    "metadata"            jsonb         DEFAULT '{}'::jsonb,

    "created_at"          timestamptz   DEFAULT now(),
    "updated_at"          timestamptz   DEFAULT now()
);

CREATE INDEX "idx_event_registrations_event_id"   ON "public"."event_registrations" ("event_id");
CREATE INDEX "idx_event_registrations_email"      ON "public"."event_registrations" ("email");
CREATE INDEX "idx_event_registrations_status"     ON "public"."event_registrations" ("status");
CREATE INDEX "idx_event_registrations_profile_id" ON "public"."event_registrations" ("profile_id");
CREATE UNIQUE INDEX "idx_event_registrations_event_email_active"
    ON "public"."event_registrations" ("event_id", "email")
    WHERE status != 'cancelled';
CREATE UNIQUE INDEX "unique_event_profile_active"
    ON "public"."event_registrations" ("event_id", "profile_id")
    WHERE profile_id IS NOT NULL AND status != 'cancelled';

COMMENT ON TABLE "public"."event_registrations" IS 'DORMANT. Used by Wrapped. RSVP-on-Cebby is killed (.impeccable.md).';


-- ============================================================================
-- 6. INDEXES (performance)
-- ============================================================================

-- ---- events ----------------------------------------------------------------

-- Core sort: chronological browsing (admin lists, calendar view).
CREATE INDEX "events_start_time_idx" ON "public"."events" ("start_time");

-- The hottest read on the directory: "upcoming published events". Partial
-- index drops drafts/hidden/cancelled from the walk. Postgres rejects
-- now()-based predicates here (functions in index predicates must be
-- IMMUTABLE), so we filter only by status; queries use start_time ordering
-- to get the upcoming subset efficiently anyway.
CREATE INDEX "events_published_idx"
    ON "public"."events" ("start_time" DESC)
    WHERE "status" = 'published';

-- Search box / matcher: trigram similarity on name.
CREATE INDEX "events_name_trgm_idx"
    ON "public"."events" USING gin ("name" extensions.gin_trgm_ops);

-- "Events at venue X" / map view.
CREATE INDEX "events_venue_id_idx"
    ON "public"."events" ("venue_id")
    WHERE "venue_id" IS NOT NULL;

-- "Events in city Y" — denormalized geographic filter.
CREATE INDEX "events_city_idx"
    ON "public"."events" ("city")
    WHERE "city" IS NOT NULL;

-- Format filter chips ("Online" / "In person").
CREATE INDEX "events_format_idx"
    ON "public"."events" ("format")
    WHERE "status" = 'published';

-- Free filter chip.
CREATE INDEX "events_is_free_idx"
    ON "public"."events" ("is_free")
    WHERE "is_free" = true AND "status" = 'published';


-- ---- event_source_links ----------------------------------------------------

CREATE INDEX "event_source_links_event_id_idx"
    ON "public"."event_source_links" ("event_id");

CREATE INDEX "event_source_links_source_idx"
    ON "public"."event_source_links" ("source");


-- ---- event_organizers ------------------------------------------------------

-- "Events by organization X" — primary org-page query.
CREATE INDEX "event_organizers_account_id_idx"
    ON "public"."event_organizers" ("account_id");


-- ---- event_tags ------------------------------------------------------------

-- "Events tagged AI" — primary filter-chip query.
CREATE INDEX "event_tags_tag_id_idx"
    ON "public"."event_tags" ("tag_id");


-- ---- accounts --------------------------------------------------------------

CREATE INDEX "accounts_organization_id_idx"
    ON "public"."accounts" ("organization_id")
    WHERE "organization_id" IS NOT NULL;

-- Cron jobs select active accounts by type. Partial index narrows the walk.
CREATE INDEX "accounts_type_active_idx"
    ON "public"."accounts" ("type")
    WHERE "is_active" = true;


-- ---- venues ----------------------------------------------------------------

CREATE INDEX "venues_city_idx"          ON "public"."venues" ("city");
CREATE INDEX "venues_parent_org_idx"    ON "public"."venues" ("parent_org_id")
    WHERE "parent_org_id" IS NOT NULL;


-- ============================================================================
-- 7. RPC functions
-- ============================================================================

-- find_event_matches — convenience RPC the ingest pipeline calls when
-- considering whether an incoming scrape should attach to an existing
-- event or create a new one. Trigram similarity + date window.
CREATE OR REPLACE FUNCTION "public"."find_event_matches"(
    p_name text,
    p_start_time timestamptz,
    p_threshold real DEFAULT 0.7,
    p_window_days int DEFAULT 1
)
RETURNS TABLE(id bigint, name text, score real)
LANGUAGE sql
STABLE
AS $$
    SELECT
        e.id,
        e.name,
        extensions.similarity(e.name, p_name) AS score
    FROM public.events e
    WHERE e.start_time BETWEEN p_start_time - (p_window_days || ' days')::interval
                           AND p_start_time + (p_window_days || ' days')::interval
      AND e.name IS NOT NULL
      AND e.status != 'hidden'
      AND extensions.similarity(e.name, p_name) >= p_threshold
    ORDER BY score DESC
    LIMIT 5;
$$;

COMMENT ON FUNCTION "public"."find_event_matches" IS 'Trigram-similarity match for ingest deduplication. Excludes hidden events so a manually-hidden duplicate doesn''t become a re-attach target.';


-- ============================================================================
-- 8. RLS policies
-- ============================================================================

-- Public-facing tables: anonymous read, service-role full access.
-- (PostgREST + supabase-js client-side reads run as `anon`.)

ALTER TABLE "public"."organizations"      ENABLE ROW LEVEL SECURITY;
ALTER TABLE "public"."accounts"           ENABLE ROW LEVEL SECURITY;
ALTER TABLE "public"."account_secrets"    ENABLE ROW LEVEL SECURITY;
ALTER TABLE "public"."venues"             ENABLE ROW LEVEL SECURITY;
ALTER TABLE "public"."events"             ENABLE ROW LEVEL SECURITY;
ALTER TABLE "public"."event_source_links" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "public"."event_organizers"   ENABLE ROW LEVEL SECURITY;
ALTER TABLE "public"."event_slugs"        ENABLE ROW LEVEL SECURITY;
ALTER TABLE "public"."tags"               ENABLE ROW LEVEL SECURITY;
ALTER TABLE "public"."event_tags"         ENABLE ROW LEVEL SECURITY;
ALTER TABLE "public"."profiles"           ENABLE ROW LEVEL SECURITY;
ALTER TABLE "public"."event_registrations" ENABLE ROW LEVEL SECURITY;

-- Public-readable directory tables.
CREATE POLICY "anon_read" ON "public"."organizations"      FOR SELECT TO anon, authenticated USING (true);
CREATE POLICY "anon_read" ON "public"."accounts"           FOR SELECT TO anon, authenticated USING (true);
CREATE POLICY "anon_read" ON "public"."venues"             FOR SELECT TO anon, authenticated USING (true);
CREATE POLICY "anon_read" ON "public"."events"             FOR SELECT TO anon, authenticated USING (status != 'hidden');
CREATE POLICY "anon_read" ON "public"."event_source_links" FOR SELECT TO anon, authenticated USING (true);
CREATE POLICY "anon_read" ON "public"."event_organizers"   FOR SELECT TO anon, authenticated USING (true);
CREATE POLICY "anon_read" ON "public"."event_slugs"        FOR SELECT TO anon, authenticated USING (true);
CREATE POLICY "anon_read" ON "public"."tags"               FOR SELECT TO anon, authenticated USING (is_canonical = true);
CREATE POLICY "anon_read" ON "public"."event_tags"         FOR SELECT TO anon, authenticated USING (true);

-- account_secrets: service_role only. NO anon/authenticated policies =
-- those roles get implicit deny.

-- Dormant user-data tables are service-role only. PWA server API routes that
-- need Wrapped / RSVP compatibility must access them through service role.


-- ============================================================================
-- 9. Grants
-- ============================================================================

GRANT USAGE ON SCHEMA "public" TO "postgres", "anon", "authenticated", "service_role";

-- All sequences and tables, default grants.
GRANT ALL ON ALL TABLES    IN SCHEMA "public" TO "postgres", "service_role";
GRANT ALL ON ALL SEQUENCES IN SCHEMA "public" TO "postgres", "service_role";
GRANT ALL ON ALL FUNCTIONS IN SCHEMA "public" TO "postgres", "service_role";

GRANT SELECT ON
    "public"."organizations",
    "public"."accounts",
    "public"."venues",
    "public"."events",
    "public"."event_organizers",
    "public"."event_slugs",
    "public"."tags",
    "public"."event_tags"
    TO "anon", "authenticated";

GRANT SELECT (
    "id",
    "event_id",
    "source",
    "source_id",
    "url",
    "ingest_kind",
    "scraped_at",
    "created_at",
    "updated_at"
) ON "public"."event_source_links" TO "anon", "authenticated";

GRANT USAGE  ON ALL SEQUENCES IN SCHEMA "public" TO "anon", "authenticated";

-- Private tables / columns: revoke explicitly because broad default grants are
-- easy to reintroduce in later migrations.
REVOKE ALL ON "public"."account_secrets" FROM "anon", "authenticated";
REVOKE ALL ON "public"."profiles" FROM "anon", "authenticated";
REVOKE ALL ON "public"."event_registrations" FROM "anon", "authenticated";
REVOKE SELECT ("raw") ON "public"."event_source_links" FROM "anon", "authenticated";

-- find_event_matches RPC.
GRANT EXECUTE ON FUNCTION "public"."find_event_matches"(text, timestamptz, real, int)
    TO "anon", "authenticated", "service_role";


-- ============================================================================
-- 10. Seed: canonical filter-chip tags
--
-- These match the chips listed in .impeccable.md ("All · This week · Free
-- · Beginner · Hiring · Online"). "All" and "This week" are app-side
-- pseudo-filters (not real tags). The rest seed here.
-- ============================================================================

INSERT INTO "public"."tags" (slug, name, kind, is_canonical, description) VALUES
    ('free',         'Free',          'other',    true, 'Event has no admission fee.'),
    ('beginner',     'Beginner',      'level',    true, 'Pitched at people new to the topic.'),
    ('hiring',       'Hiring',        'other',    true, 'Companies present are actively recruiting.'),
    ('online',       'Online',        'format',   true, 'Fully virtual / remote (no physical venue). Auto-derived from events.format=online.'),
    ('ai',           'AI',            'topic',    true, 'AI/ML focused — talks, workshops, tooling.'),
    ('web3',         'Web3',          'topic',    true, 'Blockchain, crypto, decentralized systems.'),
    ('design',       'Design',        'topic',    true, 'Product/UX/UI design events.'),
    ('mobile',       'Mobile',        'topic',    true, 'iOS, Android, cross-platform mobile development.'),
    ('devops',       'DevOps',        'topic',    true, 'Infrastructure, deployment, observability.'),
    ('security',     'Security',      'topic',    true, 'AppSec, infrastructure security, threat modelling.'),
    ('workshop',     'Workshop',      'format',   true, 'Hands-on session with exercises.'),
    ('hackathon',    'Hackathon',     'format',   true, 'Build event, typically 24h+.'),
    ('conference',   'Conference',    'format',   true, 'Multi-track, multi-day, multiple speakers.'),
    ('meetup',       'Meetup',        'format',   true, 'Recurring community gathering.');


-- ============================================================================
-- End of v2 initial schema.
--
-- Followups managed elsewhere:
--   • Data migration from v1: services/core/scripts/migrate-v1-to-v2.ts
--   • Cutover runbook: services/core/supabase/migrations-v2/README.md
-- ============================================================================
