name: Sync Typesense Records

on:
  schedule:
    # Run every day at midnight UTC
    - cron: '0 0 * * *'
  workflow_dispatch: # Allow manual trigger

jobs:
  sync-typesense:
    name: Sync Typesense Records
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Setup pnpm
        uses: pnpm/action-setup@v3
        with:
          version: 8
          run_install: false

      - name: Get pnpm store directory
        shell: bash
        run: |
          echo "STORE_PATH=$(pnpm store path --silent)" >> $GITHUB_ENV

      - name: Setup pnpm cache
        uses: actions/cache@v4
        with:
          path: ${{ env.STORE_PATH }}
          key: ${{ runner.os }}-pnpm-store-${{ hashFiles('**/pnpm-lock.yaml') }}
          restore-keys: |
            ${{ runner.os }}-pnpm-store-

      - name: Install dependencies
        run: pnpm install

      - name: Run Typesense sync script
        working-directory: apps/pwa
        run: pnpm run sync-typesense
        env:
          # Supabase environment variables (matching your .env file)
          PUBLIC_SUPABASE_URL: ${{ secrets.PUBLIC_SUPABASE_URL }}
          SUPABASE_SERVICE_ROLE_KEY: ${{ secrets.SUPABASE_SERVICE_ROLE_KEY }}

          # Typesense environment variables (matching your .env file)
          PUBLIC_TYPESENSE_HOST: ${{ secrets.PUBLIC_TYPESENSE_HOST }}
          PUBLIC_TYPESENSE_PORT: ${{ secrets.PUBLIC_TYPESENSE_PORT }}
          PUBLIC_TYPESENSE_PROTOCOL: ${{ secrets.PUBLIC_TYPESENSE_PROTOCOL }}
          TYPESENSE_ADMIN_KEY: ${{ secrets.TYPESENSE_ADMIN_KEY }}

      # @todo: setup fail notificaton later
      # - name: Send notification on failure
      #   if: failure()
      #   uses: actions/github-script@v7
      #   with:
      #     script: |
      #       await github.rest.issues.create({
      #         owner: context.repo.owner,
      #         repo: context.repo.repo,
      #         title: `Typesense sync failed - ${new Date().toISOString().split('T')[0]}`,
      #         body: `The scheduled Typesense sync workflow failed. Please check the [workflow run](${context.serverUrl}/${context.repo.owner}/${context.repo.repo}/actions/runs/${context.runId}) for details.`,
      #         labels: ['bug', 'automation']
      #       })
